security.protocol=SSL

ssl.keystore.type=PKCS12
ssl.keystore.location=/opt/kafka/config/tmp/airgap-upstream.p12
ssl.keystore.password=changeit

ssl.truststore.location=/opt/kafka/config/tmp/airgap-upstream.truststore.jks
ssl.truststore.password=changeit