id=Downstream_27
nic=eth0
targetIP=0.0.0.0
targetPort=1234
target=cmd
numReceivers=1
mtu=1500
logLevel=DEBUG
transport=tcp
tcpTLSAuthMode=pinned
tcpTLSClientAuth=require
tcpTLSCertFile=/airgap/identity/server-1.crt
tcpTLSKeyFile=/airgap/identity/server-1.key
tcpTLSTrustedKeysDir=/airgap/trusted
