# Used in some log events to identify the source
id=Gaps_14
# Kafka source. If more than one, separate the servers with a comma ,
bootstrapServers=kafka-downstream.sitia.nu:9094,kafka-downstream.sitia.nu:8094
# Topic to read
topic=gaps
# Kafka group id to use. If several threads are used, this is prepended to the thread names.
groupID=14
logLevel=DEBUG

# TLS to Kafka
# Certificate file
certFile=certs/tmp/airgap-downstream.crt
# Key file
keyFile=certs/tmp/airgap-downstream.key.enc
# Password file for the encrypted key file
#keyPasswordFile=certs/tmp/airgap-downstream.pw
# CA file
caFile=certs/tmp/kafka-ca.crt
keyPasswordFile=certs/tmp/airgap-downstream.pw
