id=Upstream_27
nic=eth0
targetIP=downstream
targetPort=1234
source=random
payloadSize=1400
eps=5
logLevel=DEBUG
transport=tcp
tcpTLSEnabled=true
tcpTLSAuthMode=pinned
tcpTLSCertFile=/airgap/identity/client-1.crt
tcpTLSKeyFile=/airgap/identity/client-1.key
tcpTLSTrustedKeysDir=/airgap/trusted
tcpRetryInterval=1000
tcpRetryTimes=0
tcpRetryErrorLevel=WARN
