id=Upstream_26
nic=eth0
targetIP=downstream
targetPort=1234
source=random
payloadSize=1400
eps=5
logLevel=DEBUG
logStatistics=0
transport=tcp
tcpTLSEnabled=false
tcpRetryInterval=1000
tcpRetryTimes=0
tcpRetryErrorLevel=WARN
